export const NUMBERS = {
  ONES: {
    0: "zero",
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
    10: "ten",
    11: "eleven",
    12: "twelve",
    13: "thirteen",
    14: "fourteen",
    15: "fifteen",
    16: "sixteen",
    17: "seventeen",
    18: "eighteen",
    19: "nineteen",
  },
  TENS: {
    2: "twenty",
    3: "thirty",
    4: "forty",
    5: "fifty",
    6: "sixty",
    7: "seventy",
    8: "eighty",
    9: "ninety",
  },
  HUNDRED: "hundred",
};

export const LARGE_NUMBERS = {
  ONES: {
    0: "thousand",
    1: "million",
    2: "billion",
    3: "trillion",
    4: "quadrillion",
    5: "quintillion",
    6: "sextillion",
    7: "septillion",
    8: "octillion",
    9: "nonillion",
  },
  TENS: {
    1: "decillion",
    2: "vigintillion",
    3: "trigintillion",
    4: "quadragintillion",
    5: "quinquagintillion",
    6: "sexagintillion",
    7: "septuagintillion",
    8: "octogintillion",
    9: "nonagintillion",
  },
  UNITS_PREFIX: {
    1: "un",
    2: "duo",
    3: "tres",
    4: "quattuor",
    5: "quin",
    6: "sex",
    7: "septen",
    8: "octo",
    9: "noven",
  },
};
